CREATE TABLE NOTICE (ID NUMBER PRIMARY KEY NOT NULL, TITLE varchar(200) NOT NULL, DESCRIPTION VARCHAR(200) NOT NULL, PUBLISH_DATE DATE NOT NULL, VISUALIZATION_DATE DATE NOT NULL);
-- Incrementing id by 50
CREATE SEQUENCE SEQ_NOTICE START WITH 1 INCREMENT BY 50;